// Generated by CoffeeScript 2.3.1
(function() {
  global.TestMLCompiler = (function() {
    class TestMLCompiler {};

    TestMLCompiler.VERSION = '0.1.4';

    TestMLCompiler.env = (global.process || {}).env || {};

    return TestMLCompiler;

  }).call(this);

}).call(this);
